# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sort.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 411)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("move_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_choosedirfolders = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choosedirfolders.setGeometry(QtCore.QRect(240, 60, 41, 21))
        self.pushButton_choosedirfolders.setText("")
        self.pushButton_choosedirfolders.setObjectName("pushButton_choosedirfolders")
        self.lineEdit_pathfolders = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pathfolders.setGeometry(QtCore.QRect(10, 60, 221, 21))
        self.lineEdit_pathfolders.setObjectName("lineEdit_pathfolders")
        self.lineEdit_extensions = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_extensions.setGeometry(QtCore.QRect(10, 290, 271, 20))
        self.lineEdit_extensions.setObjectName("lineEdit_extensions")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 360, 91, 22))
        self.pushButton_start.setText("")
        self.pushButton_start.setObjectName("pushButton_start")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.lineEdit_path.setStyleSheet("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.pushButton_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_path.setGeometry(QtCore.QRect(240, 20, 41, 21))
        self.pushButton_path.setToolTipDuration(0)
        self.pushButton_path.setStyleSheet("")
        self.pushButton_path.setText("")
        self.pushButton_path.setObjectName("pushButton_path")
        self.pushButton_add_extensions = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_extensions.setGeometry(QtCore.QRect(190, 330, 41, 21))
        self.pushButton_add_extensions.setObjectName("pushButton_add_extensions")
        self.pushButton_remove_extensions = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_extensions.setGeometry(QtCore.QRect(240, 330, 41, 21))
        self.pushButton_remove_extensions.setObjectName("pushButton_remove_extensions")
        self.listWidget_extensions = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_extensions.setGeometry(QtCore.QRect(190, 100, 91, 171))
        self.listWidget_extensions.setObjectName("listWidget_extensions")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 241, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 181, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 80, 71, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 310, 91, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_removeFolders = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_removeFolders.setGeometry(QtCore.QRect(60, 330, 41, 21))
        self.pushButton_removeFolders.setObjectName("pushButton_removeFolders")
        self.pushButton_addFolders = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addFolders.setGeometry(QtCore.QRect(10, 330, 41, 21))
        self.pushButton_addFolders.setObjectName("pushButton_addFolders")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 310, 81, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 270, 261, 16))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_settings.setGeometry(QtCore.QRect(190, 360, 91, 23))
        self.pushButton_settings.setToolTip("")
        self.pushButton_settings.setText("")
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.listWidget_categori = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_categori.setGeometry(QtCore.QRect(10, 100, 151, 171))
        self.listWidget_categori.setObjectName("listWidget_categori")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(300, 20, 271, 361))
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox_lang = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_lang.setGeometry(QtCore.QRect(110, 330, 69, 21))
        self.comboBox_lang.setObjectName("comboBox_lang")
        self.label_lang = QtWidgets.QLabel(self.centralwidget)
        self.label_lang.setGeometry(QtCore.QRect(110, 310, 71, 20))
        self.label_lang.setText("")
        self.label_lang.setObjectName("label_lang")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MoveToFolders"))
        self.pushButton_add_extensions.setText(_translate("MainWindow", "+"))
        self.pushButton_remove_extensions.setText(_translate("MainWindow", "-"))
        self.pushButton_removeFolders.setText(_translate("MainWindow", "-"))
        self.pushButton_addFolders.setText(_translate("MainWindow", "+"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

