# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 400)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_path.setSizePolicy(sizePolicy)
        self.lineEdit_path.setStyleSheet("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_path)
        self.pushButton_path = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_path.sizePolicy().hasHeightForWidth())
        self.pushButton_path.setSizePolicy(sizePolicy)
        self.pushButton_path.setMaximumSize(QtCore.QSize(41, 16777215))
        self.pushButton_path.setToolTipDuration(0)
        self.pushButton_path.setStyleSheet("")
        self.pushButton_path.setText("")
        self.pushButton_path.setObjectName("pushButton_path")
        self.horizontalLayout_2.addWidget(self.pushButton_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_pathfolders = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pathfolders.sizePolicy().hasHeightForWidth())
        self.lineEdit_pathfolders.setSizePolicy(sizePolicy)
        self.lineEdit_pathfolders.setObjectName("lineEdit_pathfolders")
        self.horizontalLayout_3.addWidget(self.lineEdit_pathfolders)
        self.pushButton_choosedirfolders = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_choosedirfolders.sizePolicy().hasHeightForWidth())
        self.pushButton_choosedirfolders.setSizePolicy(sizePolicy)
        self.pushButton_choosedirfolders.setMaximumSize(QtCore.QSize(41, 16777215))
        self.pushButton_choosedirfolders.setText("")
        self.pushButton_choosedirfolders.setObjectName("pushButton_choosedirfolders")
        self.horizontalLayout_3.addWidget(self.pushButton_choosedirfolders)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.listWidget_categori = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_categori.setObjectName("listWidget_categori")
        self.gridLayout.addWidget(self.listWidget_categori, 1, 0, 1, 1)
        self.listWidget_extensions = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_extensions.setMinimumSize(QtCore.QSize(61, 0))
        self.listWidget_extensions.setMaximumSize(QtCore.QSize(61, 16777215))
        self.listWidget_extensions.setObjectName("listWidget_extensions")
        self.gridLayout.addWidget(self.listWidget_extensions, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lineEdit_extensions = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_extensions.setObjectName("lineEdit_extensions")
        self.verticalLayout.addWidget(self.lineEdit_extensions)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_start.setMaximumSize(QtCore.QSize(88, 16777215))
        self.pushButton_start.setText("")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox_lang = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_lang.sizePolicy().hasHeightForWidth())
        self.comboBox_lang.setSizePolicy(sizePolicy)
        self.comboBox_lang.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_lang.setObjectName("comboBox_lang")
        self.horizontalLayout.addWidget(self.comboBox_lang)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_settings.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_settings.setMaximumSize(QtCore.QSize(88, 16777215))
        self.pushButton_settings.setToolTip("")
        self.pushButton_settings.setText("")
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.horizontalLayout.addWidget(self.pushButton_settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Moving To Folders"))
